spring.application.name=service-registry
server.port=8761
#by default the port is this only 
server.servlet.context-path=/registry

eureka.instance.hostname=localhost

#eureka client cannot add registry and also cannot fetch the registry
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false