spring.application.name=api-gateway

server.port=8080

eureka.client.service-url.defaultZone=http://localhost:8761/registry/eureka

spring.cloud.gateway.discovery.locator.enabled=true
#only this is sufficient for this to run on every single server 